"""empty message

Revision ID: b36edb3b397b
Revises: 
Create Date: 2020-05-16 23:55:00.481524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b36edb3b397b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iss_fact',
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.Column('utc_timestamp', sa.Integer(), nullable=False),
    sa.Column('utc_date', sa.String(length=25), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('utc_insert_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('iss_fact')
    # ### end Alembic commands ###
